"""initial schema

Revision ID: ec1d112d18e8
Revises: 
Create Date: 2026-07-22 00:56:10.549899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ec1d112d18e8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('display_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories')),
    sa.UniqueConstraint('name', name=op.f('uq_categories_name'))
    )
    op.create_table('monthly_settlements',
    sa.Column('year_month', sa.String(length=7), nullable=False),
    sa.Column('status', sa.String(length=30), server_default='in_progress', nullable=False),
    sa.Column('confirmed_at_user_a', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_at_user_b', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('has_stale_updates', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('in_progress', 'closed', 'partially_confirmed', 'settled')", name=op.f('ck_monthly_settlements_status')),
    sa.PrimaryKeyConstraint('year_month', name=op.f('pk_monthly_settlements'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('theme_preference', sa.String(length=10), server_default='light', nullable=False),
    sa.Column('display_color', sa.String(length=7), nullable=True),
    sa.Column('tokens_valid_after', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("theme_preference IN ('light', 'dark')", name=op.f('ck_users_theme_preference')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=50), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_events_actor_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events'))
    )
    op.create_index('ix_events_event_type_occurred_at', 'events', ['event_type', 'occurred_at'], unique=False)
    op.create_index('ix_events_occurred_at', 'events', ['occurred_at'], unique=False)
    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paid_by', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('occurred_on', sa.Date(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('payment_method', sa.String(length=20), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('source_staging_id', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("payment_method IN ('cash', 'credit_card', 'paypay', 'wechatpay')", name=op.f('ck_expenses_payment_method')),
    sa.CheckConstraint('amount > 0', name=op.f('ck_expenses_amount_positive')),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_expenses_category_id_categories'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['paid_by'], ['users.id'], name=op.f('fk_expenses_paid_by_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_staging_id'], ['paypay_import_staging.id'], name='fk_expenses_source_staging_id_paypay_import_staging', ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_expenses'))
    )
    op.create_index('ix_expenses_category_id_occurred_on', 'expenses', ['category_id', 'occurred_on'], unique=False)
    op.create_index('ix_expenses_occurred_on', 'expenses', ['occurred_on'], unique=False)
    op.create_index('ix_expenses_paid_by_occurred_on', 'expenses', ['paid_by', 'occurred_on'], unique=False)
    op.create_table('paypay_import_staging',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imported_by', sa.Integer(), nullable=False),
    sa.Column('imported_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('occurred_on', sa.Date(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('merchant_name', sa.Text(), nullable=True),
    sa.Column('paypay_txn_id', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('linked_expense_id', sa.Integer(), nullable=True),
    sa.Column('raw_row', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'adopted', 'excluded')", name=op.f('ck_paypay_import_staging_status')),
    sa.ForeignKeyConstraint(['imported_by'], ['users.id'], name=op.f('fk_paypay_import_staging_imported_by_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['linked_expense_id'], ['expenses.id'], name=op.f('fk_paypay_import_staging_linked_expense_id_expenses'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_paypay_import_staging')),
    sa.UniqueConstraint('imported_by', 'paypay_txn_id', name='uq_paypay_import_staging_txn')
    )
    op.create_index('ix_paypay_import_staging_imported_by_status', 'paypay_import_staging', ['imported_by', 'status'], unique=False)
    op.create_index('ix_paypay_import_staging_occurred_on', 'paypay_import_staging', ['occurred_on'], unique=False)
    # ### end Alembic commands ###

    # --- 手動追加: use_alter=True の FK は Alembic autogenerate では
    # ALTER TABLE の追加が漏れることがあるため、明示的にここで作成 ---
    op.create_foreign_key(
        'fk_expenses_source_staging_id_paypay_import_staging',
        'expenses', 'paypay_import_staging',
        ['source_staging_id'], ['id'],
        ondelete='SET NULL',
    )


def downgrade() -> None:
    """Downgrade schema."""
    # --- 手動追加: 上で明示的に作った FK を先に drop する ---
    op.drop_constraint(
        'fk_expenses_source_staging_id_paypay_import_staging',
        'expenses', type_='foreignkey',
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_paypay_import_staging_occurred_on', table_name='paypay_import_staging')
    op.drop_index('ix_paypay_import_staging_imported_by_status', table_name='paypay_import_staging')
    op.drop_table('paypay_import_staging')
    op.drop_index('ix_expenses_paid_by_occurred_on', table_name='expenses')
    op.drop_index('ix_expenses_occurred_on', table_name='expenses')
    op.drop_index('ix_expenses_category_id_occurred_on', table_name='expenses')
    op.drop_table('expenses')
    op.drop_index('ix_events_occurred_at', table_name='events')
    op.drop_index('ix_events_event_type_occurred_at', table_name='events')
    op.drop_table('events')
    op.drop_table('users')
    op.drop_table('monthly_settlements')
    op.drop_table('categories')
    # ### end Alembic commands ###
